// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Base62 is an autogenerated mock type for the Base62 type
type Base62 struct {
	mock.Mock
}

// Decode provides a mock function with given fields: str
func (_m *Base62) Decode(str string) string {
	ret := _m.Called(str)

	if len(ret) == 0 {
		panic("no return value specified for Decode")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(string) string); ok {
		r0 = rf(str)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// Encode provides a mock function with given fields: code
func (_m *Base62) Encode(code int) string {
	ret := _m.Called(code)

	if len(ret) == 0 {
		panic("no return value specified for Encode")
	}

	var r0 string
	if rf, ok := ret.Get(0).(func(int) string); ok {
		r0 = rf(code)
	} else {
		r0 = ret.Get(0).(string)
	}

	return r0
}

// NewBase62 creates a new instance of Base62. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBase62(t interface {
	mock.TestingT
	Cleanup(func())
}) *Base62 {
	mock := &Base62{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
