// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	model "github.com/TNJKL/bookmark-management/internal/model"
	mock "github.com/stretchr/testify/mock"
)

// HealthChecker is an autogenerated mock type for the HealthChecker type
type HealthChecker struct {
	mock.Mock
}

// HealthCheck provides a mock function with no fields
func (_m *HealthChecker) HealthCheck() (model.HealthCheckResponse, error) {
	ret := _m.Called()

	if len(ret) == 0 {
		panic("no return value specified for HealthCheck")
	}

	var r0 model.HealthCheckResponse
	var r1 error
	if rf, ok := ret.Get(0).(func() (model.HealthCheckResponse, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() model.HealthCheckResponse); ok {
		r0 = rf()
	} else {
		r0 = ret.Get(0).(model.HealthCheckResponse)
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewHealthChecker creates a new instance of HealthChecker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewHealthChecker(t interface {
	mock.TestingT
	Cleanup(func())
}) *HealthChecker {
	mock := &HealthChecker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
