basePath: /
definitions:
  model.HealthCheckResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
host: localhost:8080
info:
  contact: {}
  description: Đây là tài liệu API cho hệ thống quản lý Bookmark.
  title: Bookmark Management API
  version: "1.0"
paths:
  /health-check:
    get:
      description: Trả về trạng thái hoạt động hiện tại, tên dịch vụ và instance ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthCheckResponse'
        "500":
          description: Lỗi hệ thống nội bộ
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Kiểm tra trạng thái hệ thống
      tags:
      - System
swagger: "2.0"
