basePath: /
definitions:
  handler.shortenInputBody:
    properties:
      exp:
        type: integer
      url:
        type: string
    type: object
  model.HealthCheckResponse:
    properties:
      instance_id:
        type: string
      message:
        type: string
      service_name:
        type: string
    type: object
info:
  contact: {}
  description: API Swagger for Bookmark-Management.
  title: Bookmark Management API
  version: 1.0.0
paths:
  /genpass:
    get:
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthCheckResponse'
      summary: Generate a random password
      tags:
      - password
  /health-check:
    get:
      description: Trả về trạng thái hoạt động hiện tại, tên dịch vụ và instance ID
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.HealthCheckResponse'
        "500":
          description: Lỗi hệ thống nội bộ
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Kiểm tra trạng thái hệ thống
      tags:
      - health-check
  /v1/links/shorten:
    post:
      consumes:
      - application/json
      description: Generate shorten url based on original url that last upto 7 days
      parameters:
      - description: Input required
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/handler.shortenInputBody'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      tags:
      - link
swagger: "2.0"
